package br.com.ditwowin.api.shared;

public class Utils {
    public static final String ERROR_ACCOUNT_EXISTS_ACCOUNT = "THERE IS AN ACCOUNT FOR THIS CUSTOMER";
    public static final String SUCCESS_ACCOUNT_CREATED = "ACCOUNT CREATED SUCCESSFULLY";
    public static final String SUCCESS_ACCOUNT_STATUS_UPDATED = "ACCOUNT STATUS HAS BEEN UPDATED";

    public static final String SUCCESS_TRANSACTION_WITH_DRAWMONEY = "MONEY WITHDRAWN SUCCESSFULLY";
    public static final String ERROR_TRANSACTION_WITH_DRAWMONEY = "THERE WAS A PROBLEM WITHDRAWING MONEY";

    public static final String SUCCESS_TRANSACTION_WITH_DEPOSIT = "MONEY DEPOSIT SUCCESSFULLY";
    public static final String ERROR_TRANSACTION_WITH_DEPOSIT = "THERE WAS A PROBLEM DEPOSIT MONEY";

    public static final String ERROR_TRANSACTION_WITH_FILTER = "THERE WAS AN ERROR FILTERING THE DATA";
}
